[changelog]
header = """
# Changelog
All notable changes to this project will be documented in this file.
"""

# Optional: output older releases in descending order
sort = "desc"
template = """
## [{{version}}] - {{date}}
{% if commits | length == 0 %}
_No changes._
{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | trim }} ([{{ commit.id | truncate(length=7) }}]({{ commit.remote.url }}/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""

[git]
tag_pattern = "v[0-9]+.[0-9]+.*"  # Matches tags like v1.0.0
commit_parsers = [
  { message = "^feat\\(.*\\):", group = "Features" },
  { message = "^fix\\(.*\\):", group = "Bug Fixes" },
  { message = "^docs\\(.*\\):", group = "Documentation" },
  { message = "^style\\(.*\\):", group = "Styles" },
  { message = "^refactor\\(.*\\):", group = "Refactoring" },
  { message = "^test\\(.*\\):", group = "Testing" },
  { message = "^chore\\(.*\\):", group = "Chores" },
  { message = "^ci\\(.*\\):", group = "CI" }
]
filter_commits = true
sort_commits = "oldest"

[remote]
name = "origin"
